// CSL formatting engine — pure (no DB, no ctx), wraps citeproc-js with vendored style +
// locale XML (src/server/csl/styles, generated by scripts/fetch-csl-styles.ts).
// Formatting NEVER throws: a catastrophic engine failure degrades to plain
// "{title} ({year})." entries so a single odd item can't take down a bibliography.

import CSL from "citeproc";
import { xml as vancouverXml } from "./styles/vancouver";
import { xml as amaXml } from "./styles/ama";
import { xml as apaXml } from "./styles/apa";
import { xml as nlmXml } from "./styles/nlm";
import { xml as enUsLocale } from "./locales/en-us";

export const CSL_STYLES = [
  { id: "vancouver", label: "Vancouver", numeric: true },
  { id: "ama", label: "AMA (11th ed.)", numeric: true },
  { id: "apa", label: "APA (7th ed.)", numeric: false },
  { id: "nlm", label: "NLM (grant proposals)", numeric: true },
] as const;

export type CslStyleId = (typeof CSL_STYLES)[number]["id"];
export const DEFAULT_STYLE_ID: CslStyleId = "vancouver";
export const CSL_STYLE_IDS = CSL_STYLES.map((s) => s.id) as [CslStyleId, ...CslStyleId[]];

const STYLE_XML: Record<CslStyleId, string> = {
  vancouver: vancouverXml,
  ama: amaXml,
  apa: apaXml,
  nlm: nlmXml,
};

export function isNumericStyle(styleId: CslStyleId): boolean {
  return CSL_STYLES.find((s) => s.id === styleId)?.numeric ?? true;
}

// A CSL-JSON item; id is OUR ReferenceEntry id so callers key results by reference.
export type CslItem = { id: string; type: string } & Record<string, unknown>;

export interface FormattedReference {
  referenceId: string;
  index: number; // 1-based position in the rendered bibliography
  citeMarker: string; // in-text form: "1." / "(1)" for numeric styles, "(Author, Year)" for APA
  html: string;
  text: string;
}

function stripTags(html: string): string {
  return html
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)))
    .replace(/\s+/g, " ")
    .trim();
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function fallbackEntries(items: CslItem[], order: string[]): FormattedReference[] {
  const byId = new Map(items.map((item) => [item.id, item]));
  return order
    .filter((id) => byId.has(id))
    .map((id, i) => {
      const item = byId.get(id)!;
      const title = typeof item.title === "string" ? item.title : "Untitled reference";
      const year = yearOf(item);
      const text = `${title}${year ? ` (${year})` : ""}.`;
      return {
        referenceId: id,
        index: i + 1,
        citeMarker: String(i + 1),
        html: escapeHtml(text),
        text,
      };
    });
}

function yearOf(item: CslItem): number | null {
  const issued = item.issued as { "date-parts"?: unknown } | undefined;
  const parts = issued?.["date-parts"];
  const year = Array.isArray(parts) && Array.isArray(parts[0]) ? parts[0][0] : null;
  return typeof year === "number" ? year : null;
}

// orderedIds = first-use order supplied by the caller (the manuscript editor's citation
// order); numeric styles number by it. Ids not present in `items` are ignored; items not
// present in orderedIds are appended in the given items order.
export function formatBibliographyPure(
  items: CslItem[],
  styleId: CslStyleId,
  orderedIds?: string[],
): { entries: FormattedReference[] } {
  if (items.length === 0) return { entries: [] };

  const known = new Set(items.map((i) => i.id));
  const order: string[] = [];
  for (const id of orderedIds ?? []) {
    if (known.has(id) && !order.includes(id)) order.push(id);
  }
  for (const item of items) {
    if (!order.includes(item.id)) order.push(item.id);
  }

  try {
    const byId = new Map(items.map((item) => [item.id, item]));
    const sys = {
      retrieveLocale: () => enUsLocale,
      retrieveItem: (id: string) => (byId.get(id) ?? { id, type: "article-journal" }) as Record<string, unknown>,
    };
    const engine = new CSL.Engine(sys, STYLE_XML[styleId], "en-US", true);
    engine.setOutputFormat("html");
    engine.updateItems(order);

    const bib = engine.makeBibliography();
    if (!bib) return { entries: fallbackEntries(items, order) };
    const [meta, rendered] = bib;

    const numeric = isNumericStyle(styleId);
    const entries: FormattedReference[] = meta.entry_ids.map((idGroup, i) => {
      const referenceId = idGroup[0] ?? order[i] ?? "";
      const html = (rendered[i] ?? "").trim();
      // Numeric styles: the marker IS the bibliography position (which follows
      // updateItems order). previewCitationCluster can't be used — it previews an
      // isolated citation and always renumbers from 1.
      let citeMarker = String(i + 1);
      if (!numeric) {
        try {
          citeMarker =
            engine
              .previewCitationCluster(
                { citationItems: [{ id: referenceId }], properties: { noteIndex: 0 } },
                [],
                [],
                "text",
              )
              .trim() || citeMarker;
        } catch {
          // keep the positional fallback
        }
      }
      return {
        referenceId,
        index: i + 1,
        citeMarker,
        html,
        text: stripTags(html),
      };
    });
    return { entries };
  } catch {
    return { entries: fallbackEntries(items, order) };
  }
}
