// Golden-fixture tests: every fixture in __fixtures__/ was generated by the
// INDEPENDENT Python/scipy reference (scripts/generate-stats-fixtures.py); this
// suite asserts that computeMeta reproduces the reference numbers.
//
// Tolerances (pinned): 1e-8 for y/se/tau2/Q/I2/weights, 1e-6 for p-values and
// CI bounds (incl. back-transformed display values).

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { computeMeta } from "./meta";
import type { EffectMeasureId, StudyEffectInput } from "./types";

const TOL_ESTIMATE = 1e-8;
const TOL_P_CI = 1e-6;

interface FixtureDisplay {
  estimate: number;
  ciLow: number;
  ciHigh: number;
}

interface FixtureStudy {
  id: string;
  label: string;
  y: number;
  se: number;
  ciLow: number;
  ciHigh: number;
  display: FixtureDisplay;
  weightFixedPct: number;
  weightRandomPct: number;
}

interface FixturePooled {
  y: number;
  se: number;
  ciLow: number;
  ciHigh: number;
  display: FixtureDisplay;
  z: number;
  p: number;
}

interface Fixture {
  name: string;
  measure: EffectMeasureId;
  studies: StudyEffectInput[];
  expected: {
    studies: FixtureStudy[];
    excludedIds: string[];
    fixed: FixturePooled | null;
    random: FixturePooled | null;
    heterogeneity: { q: number; df: number; p: number; i2: number; tau2: number } | null;
  };
}

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "__fixtures__");
const files = readdirSync(FIXTURES_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

const close = (actual: number, expected: number, tol: number) =>
  expect(Math.abs(actual - expected), `expected ${actual} ≈ ${expected}`).toBeLessThanOrEqual(
    tol,
  );

function assertDisplay(actual: FixtureDisplay, expected: FixtureDisplay) {
  close(actual.estimate, expected.estimate, TOL_P_CI);
  close(actual.ciLow, expected.ciLow, TOL_P_CI);
  close(actual.ciHigh, expected.ciHigh, TOL_P_CI);
}

function assertPooled(actual: FixturePooled | null, expected: FixturePooled | null) {
  if (expected === null) {
    expect(actual).toBeNull();
    return;
  }
  expect(actual).not.toBeNull();
  close(actual!.y, expected.y, TOL_ESTIMATE);
  close(actual!.se, expected.se, TOL_ESTIMATE);
  close(actual!.ciLow, expected.ciLow, TOL_P_CI);
  close(actual!.ciHigh, expected.ciHigh, TOL_P_CI);
  close(actual!.z, expected.z, TOL_ESTIMATE);
  close(actual!.p, expected.p, TOL_P_CI);
  assertDisplay(actual!.display, expected.display);
}

describe("golden fixtures (Python/scipy reference)", () => {
  expect(files.length).toBeGreaterThan(0);

  for (const file of files) {
    it(`reproduces ${file}`, () => {
      const fixture = JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf8")) as Fixture;
      const result = computeMeta(fixture.studies, { measure: fixture.measure });

      // Inclusion/exclusion sets, input order preserved.
      expect(result.studies.map((s) => s.id)).toEqual(fixture.expected.studies.map((s) => s.id));
      expect(result.excluded.map((s) => s.id)).toEqual(fixture.expected.excludedIds);

      // Per-study estimates and weights.
      for (let i = 0; i < fixture.expected.studies.length; i++) {
        const exp = fixture.expected.studies[i]!;
        const act = result.studies[i]!;
        expect(act.label).toBe(exp.label);
        close(act.y, exp.y, TOL_ESTIMATE);
        close(act.se, exp.se, TOL_ESTIMATE);
        close(act.ciLow, exp.ciLow, TOL_P_CI);
        close(act.ciHigh, exp.ciHigh, TOL_P_CI);
        close(act.weightFixedPct, exp.weightFixedPct, TOL_ESTIMATE);
        close(act.weightRandomPct, exp.weightRandomPct, TOL_ESTIMATE);
        assertDisplay(act.display, exp.display);
      }

      // Pooled estimates.
      assertPooled(result.fixed, fixture.expected.fixed);
      assertPooled(result.random, fixture.expected.random);

      // Heterogeneity.
      if (fixture.expected.heterogeneity === null) {
        expect(result.heterogeneity).toBeNull();
      } else {
        const exp = fixture.expected.heterogeneity;
        expect(result.heterogeneity).not.toBeNull();
        const act = result.heterogeneity!;
        expect(act.df).toBe(exp.df);
        close(act.q, exp.q, TOL_ESTIMATE);
        close(act.tau2, exp.tau2, TOL_ESTIMATE);
        close(act.i2, exp.i2, TOL_ESTIMATE);
        close(act.p, exp.p, TOL_P_CI);
      }
    });
  }
});
