// Student-t distribution: CDF (via the regularized incomplete beta) and the
// quantile qt(p, df) (inverse CDF via safeguarded Newton refinement).
//
// Pure, deterministic numerics — no dependencies. The incomplete beta uses the
// Numerical Recipes continued fraction (betacf, modified Lentz) with the Lanczos
// log-gamma shared from chisq.ts. qt is pinned against scipy.stats.t.ppf values
// generated by scripts/generate-stats-fixtures.py (__fixtures__/pins-qt.json,
// asserted in fixtures.test.ts at 1e-8) for df ∈ {1,2,3,5,10,30,100} ×
// p ∈ {0.6, 0.9, 0.975, 0.995}.
//
// Identities used (published math, mirrored independently by the Python reference):
// - For t >= 0:  P(T > t) = 0.5 · I_x(df/2, 1/2)  with  x = df / (df + t²).
// - pdf(t) = exp(lgamma((df+1)/2) − lgamma(df/2) − 0.5·ln(df·π)) · (1 + t²/df)^−((df+1)/2)

import { lgamma } from "./chisq";

const ITMAX = 300;
const EPS = 1e-15; // relative convergence threshold (double precision)
const FPMIN = 1e-300; // guard against division underflow in Lentz's method
const HALF_LOG_PI = 0.5723649429247001; // 0.5 * ln(pi)

// Continued-fraction for the incomplete beta (Numerical Recipes betacf).
function betacf(a: number, b: number, x: number): number {
  const qab = a + b;
  const qap = a + 1;
  const qam = a - 1;
  let c = 1;
  let d = 1 - (qab * x) / qap;
  if (Math.abs(d) < FPMIN) d = FPMIN;
  d = 1 / d;
  let h = d;
  for (let m = 1; m <= ITMAX; m++) {
    const m2 = 2 * m;
    let aa = (m * (b - m) * x) / ((qam + m2) * (a + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < FPMIN) d = FPMIN;
    c = 1 + aa / c;
    if (Math.abs(c) < FPMIN) c = FPMIN;
    d = 1 / d;
    h *= d * c;
    aa = (-(a + m) * (qab + m) * x) / ((a + m2) * (qap + m2));
    d = 1 + aa * d;
    if (Math.abs(d) < FPMIN) d = FPMIN;
    c = 1 + aa / c;
    if (Math.abs(c) < FPMIN) c = FPMIN;
    d = 1 / d;
    const del = d * c;
    h *= del;
    if (Math.abs(del - 1) < EPS) break;
  }
  return h;
}

/** Regularized incomplete beta I_x(a, b). Requires a, b >= 0.5 (this library's use). */
export function ibeta(a: number, b: number, x: number): number {
  if (!Number.isFinite(a) || !Number.isFinite(b) || Number.isNaN(x) || a <= 0 || b <= 0) {
    return NaN;
  }
  if (x <= 0) return 0;
  if (x >= 1) return 1;
  const bt = Math.exp(
    lgamma(a + b) - lgamma(a) - lgamma(b) + a * Math.log(x) + b * Math.log(1 - x),
  );
  return x < (a + 1) / (a + b + 2) ? (bt * betacf(a, b, x)) / a : 1 - (bt * betacf(b, a, 1 - x)) / b;
}

/** Student-t CDF P(T <= t) with df degrees of freedom. */
export function pt(t: number, df: number): number {
  if (Number.isNaN(t) || !Number.isFinite(df) || df <= 0) return NaN;
  if (t === Infinity) return 1;
  if (t === -Infinity) return 0;
  const x = df / (df + t * t);
  const halfTail = 0.5 * ibeta(df / 2, 0.5, x);
  return t >= 0 ? 1 - halfTail : halfTail;
}

/** Two-sided p-value 2·P(T > |t|) — the shape Egger's test reports. */
export function studentTwoSidedP(t: number, df: number): number {
  if (Number.isNaN(t) || !Number.isFinite(df) || df <= 0) return NaN;
  if (!Number.isFinite(t)) return 0;
  return ibeta(df / 2, 0.5, df / (df + t * t));
}

// Student-t density (used as the Newton derivative in qt).
function dt(t: number, df: number): number {
  const logNorm = lgamma((df + 1) / 2) - lgamma(df / 2) - 0.5 * Math.log(df) - HALF_LOG_PI;
  return Math.exp(logNorm - ((df + 1) / 2) * Math.log(1 + (t * t) / df));
}

/**
 * Inverse Student-t CDF (quantile). Returns ±Infinity at p = 0/1, NaN outside [0, 1]
 * or for invalid df. Safeguarded Newton on pt() with a bisection fallback — accuracy
 * well beyond the 1e-8 pin tolerance against scipy.stats.t.ppf.
 */
export function qt(p: number, df: number): number {
  if (Number.isNaN(p) || p < 0 || p > 1 || !Number.isFinite(df) || df <= 0) return NaN;
  if (p === 0) return -Infinity;
  if (p === 1) return Infinity;
  if (p === 0.5) return 0;
  // Symmetry: solve in the upper half only.
  if (p < 0.5) return -qt(1 - p, df);

  // Bracket [lo, hi] with pt(lo) <= p <= pt(hi); expand hi geometrically from 1.
  let lo = 0;
  let hi = 1;
  for (let i = 0; i < 400 && pt(hi, df) < p; i++) {
    lo = hi;
    hi *= 2;
  }

  // Newton from the bracket midpoint, falling back to bisection whenever the step
  // leaves the bracket (pt is monotone, so the bracket always contains the root).
  let t = (lo + hi) / 2;
  for (let i = 0; i < 100; i++) {
    const f = pt(t, df) - p;
    if (f > 0) hi = t;
    else lo = t;
    const deriv = dt(t, df);
    let next = deriv > 0 ? t - f / deriv : NaN;
    if (!Number.isFinite(next) || next <= lo || next >= hi) next = (lo + hi) / 2;
    if (Math.abs(next - t) <= 1e-14 * Math.max(1, Math.abs(next))) {
      t = next;
      break;
    }
    t = next;
  }
  return t;
}
