// One-shot dev script: vendors CSL style + locale XML from the official
// citation-style-language repos into committed TS string modules (bundler-safe — no
// fs.readFile of .csl assets at runtime, works in any build target). Re-run only to
// refresh styles: npx tsx scripts/fetch-csl-styles.ts
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

// The Zotero style repository serves the current CSL XML for every registered style id
// (raw.githubusercontent is not reliably reachable from every network).
const STYLES_BASE = "https://www.zotero.org/styles";
const LOCALES_URL =
  "https://cdn.jsdelivr.net/gh/citation-style-language/locales/locales-en-US.xml";

// slug (our id) → Zotero style id
const STYLES: Record<string, string> = {
  vancouver: "vancouver",
  ama: "american-medical-association",
  apa: "apa",
  nlm: "national-library-of-medicine-grant-proposals",
};

const OUT_STYLES = path.join(process.cwd(), "src/server/csl/styles");
const OUT_LOCALES = path.join(process.cwd(), "src/server/csl/locales");

function toModule(xml: string, source: string): string {
  return (
    `// Vendored from ${source}\n` +
    `// CSL styles/locales are CC-BY-SA 3.0 (see the XML header). Generated by\n` +
    `// scripts/fetch-csl-styles.ts — do not hand-edit.\n` +
    `export const xml = ${JSON.stringify(xml)};\n`
  );
}

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`${url} → HTTP ${res.status}`);
  const text = await res.text();
  if (!text.includes("<style") && !text.includes("<locale")) {
    throw new Error(`${url} did not return CSL/locale XML`);
  }
  return text;
}

async function main() {
  mkdirSync(OUT_STYLES, { recursive: true });
  mkdirSync(OUT_LOCALES, { recursive: true });

  for (const [slug, styleId] of Object.entries(STYLES)) {
    const url = `${STYLES_BASE}/${styleId}`;
    const xml = await fetchText(url);
    writeFileSync(path.join(OUT_STYLES, `${slug}.ts`), toModule(xml, url));
    console.log(`✔ style ${slug} (${styleId}, ${Math.round(xml.length / 1024)} kB)`);
  }

  const locale = await fetchText(LOCALES_URL);
  writeFileSync(path.join(OUT_LOCALES, "en-us.ts"), toModule(locale, LOCALES_URL));
  console.log(`✔ locale en-US (${Math.round(locale.length / 1024)} kB)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
